Models/Announcement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace VeritabaniProjesi.Models
{
    public class Announcement
    {
        [Key, NotNull, MaxLength(40), Required]
        public string Title { get; set; }
        public string Content { get; set; }
        [Display(Name = "Linkler(\";\" sembolu ile ayirin.)")]public string SourceListString { get; set; }

        [NotMapped]
        public List<string> SourceList
        {
            get
            {
                if (SourceListString == null)
                    return new List<string>();

                return SourceListString.Split(';').ToList();
            }

            set
            {
                SourceListString = "";
                foreach (string s in value)
                    SourceListString += s + ';';
                
            }
        }

        [DataType(DataType.DateTime)] public DateTime Date { get; set; }
    }
}

Controllers/AnnouncementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VeritabaniProjesi.Data;
using VeritabaniProjesi.Models;

namespace VeritabaniProjesi.Controllers
{
    public class AnnouncementsController : Controller
    {
        private readonly BasicDataContext _context;
        private readonly UserManager<MyUser> _userManager;


        public AnnouncementsController(BasicDataContext context, UserManager<MyUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Announcements
        public async Task<IActionResult> Index()
        {
            return View(await _context.Announcements.ToListAsync());
        }

        // GET: Announcements/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var announcement = await _context.Announcements
                .FirstOrDefaultAsync(m => m.Title == id);
            if (announcement == null)
            {
                return NotFound();
            }

            return View(announcement);
        }

        // GET: Announcements/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Announcements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Content,Date, SourceListString")] Announcement announcement)
        {
            MyUser user  = await _userManager.GetUserAsync(User);
            if (user == null || user.IsAdmin == false)
                return null;


            if (ModelState.IsValid)
            {
                announcement.Date = DateTime.UtcNow;
                announcement.SourceList = announcement.SourceListString.Split(';').ToList();
                _context.Add(announcement);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(announcement);
        }

        // GET: Announcements/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(string id)
        {
            MyUser user  = await _userManager.GetUserAsync(User);
            if (user == null || user.IsAdmin == false)
                return null;

            if (id == null)
            {
                return NotFound();
            }

            var announcement = await _context.Announcements.FindAsync(id);
            if (announcement == null)
            {
                return NotFound();
            }
            return View(announcement);
        }

        // POST: Announcements/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Title,Content, Date, SourceListString")] Announcement announcement)
        {
            MyUser user  = await _userManager.GetUserAsync(User);
            if (user == null || user.IsAdmin == false)
                return null;

            if (id != announcement.Title)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(announcement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnnouncementExists(announcement.Title))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(announcement);
        }

        // GET: Announcements/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(string id)
        {
            MyUser user  = await _userManager.GetUserAsync(User);
            if (user == null || user.IsAdmin == false)
                return null;

            if (id == null)
            {
                return NotFound();
            }

            var announcement = await _context.Announcements
                .FirstOrDefaultAsync(m => m.Title == id);
            if (announcement == null)
            {
                return NotFound();
            }

            return View(announcement);
        }

        // POST: Announcements/Delete/5
        [HttpPost, ActionName("Delete"), Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            MyUser user  = await _userManager.GetUserAsync(User);
            if (user == null || user.IsAdmin == false)
                return null;

            var announcement = await _context.Announcements.FindAsync(id);
            _context.Announcements.Remove(announcement);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnnouncementExists(string id)
        {
            return _context.Announcements.Any(e => e.Title == id);
        }
    }
}

Controllers/TitlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Loader;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VeritabaniProjesi.Data;
using VeritabaniProjesi.Models;
using VeritabaniProjesi.ViewModel;

namespace VeritabaniProjesi.Controllers
{
    public class TitlesController : Controller
    {
        private readonly BasicDataContext _context;
        private readonly UserManager<MyUser> _userManager;


        public TitlesController(BasicDataContext context, UserManager<MyUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Titles
        public async Task<IActionResult> Index(string searchString)
        {
            var pages = from t in _context.Titles select t;
            if (!string.IsNullOrEmpty(searchString))
                pages = pages.Where(s => s.PostTitle.ToLower().Contains(searchString.ToLower()));


            var dataContents = pages.Include(t => t.Question);

            return View(await dataContents.ToListAsync());
        }

        // GET: Titles/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Titles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken, Authorize]
        public async Task<IActionResult> Create([Bind("PostTitle, Content")] CreateTitleViewModel ctvm)
        {
            Title title = new Title();

            if (ModelState.IsValid)
            {
                SetTitleValuesToDefault(ref title);
                title.PostTitle = ctvm.PostTitle;
                title.Date = DateTime.Now;

                var user  = _userManager.GetUserAsync(User);

                title.Question = new Post
                {
                    PostTitle = title.PostTitle,
                    Date = title.Date,
                    Sender = user.Result.NickName,
                    Rating = 0,
                    Content = ctvm.Content
                };

                title.QuestionId = title.Question.Id;

                _context.Add(title);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Posts", new{title = title.PostTitle});
            }

            return View(ctvm);
        }

     

 

        // GET: Titles/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var title = await _context.Titles
                .Include(t => t.Question)
                .FirstOrDefaultAsync(m => m.PostTitle == id);
            if (title == null)
            {
                return NotFound();
            }

            return View(title);
        }

        // POST: Titles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken, Authorize]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var title = await _context.Titles.FindAsync(id);
            _context.Titles.Remove(title);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TitleExists(string id)
        {
            return _context.Titles.Any(e => e.PostTitle == id);
        }

        private void SetTitleValuesToDefault(ref Title title)
        {
            title.Date = DateTime.Now;
            //title.QuestionId = ;
            //title.Question = ;
        }
    }
}

Views/Shared/PartialViews/_Announcements.cshtml
@model IEnumerable<VeritabaniProjesi.Models.Announcement>

<hr />
@foreach (var annoucment in Model)
{
    <div style="display: table-row">
        <h3>@annoucment.Title</h3>
        <p class="lead">@annoucment.Content</p>
        <p>@annoucment.Date</p>

        
        <ul class="list-group">
        @foreach (var source in annoucment.SourceList)
        {
            <li class="list-group-item">
                <a href ="@source">@source</a>
            </li>
            
        }
        </ul>
        <hr />
    </div>
}

Views/Shared/PartialViews/_Footer.cshtml
<footer class="page-footer font-small pt-4" style="background-color: #45526e; margin-top:20px;">
    <div class="container text-center text-md-left">
        <div class="row text-center text-md-left mt-3 pb-3">
            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                <h6 class="text-uppercase mb-4 font-weight-bold">degistir.org</h6>
                <p>
                    Dünyanın değişim platformu
                </p>
                <p>
                    455.053.917 kişi harekete geçiyor. Her gün kampanyalar başarıya ulaşıyor.
                </p>
            </div>
            <hr class="w-100 clearfix d-md-none">
            <hr class="w-100 clearfix d-md-none">
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                <h6 class="text-uppercase mb-4 font-weight-bold">Linkler</h6>
                <p>
                    <a asp-controller="Home" asp-action="Index">Biz Kimiz</a>
                </p>
                <p>
                    <a asp-controller="Home" asp-action="Privacy">Gizlilik ve Güvenlik Politikası</a>
                </p>
            </div>
            <hr class="w-100 clearfix d-md-none">
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                <h6 class="text-uppercase mb-4 font-weight-bold">İletişim</h6>
                <p>
                    <i class="fa fa-home mr-3"></i> Ankara, Çankaya, TR
                </p>
                <p>
                    <i class="fa fa-envelope mr-3"></i> info@degistir.org
                </p>
                <p>
                    <i class="fa fa-phone mr-3"></i> + 90 234 567 88
                </p>
                <p>
                    <i class="fa fa-print mr-3"></i> + 90 234 567 89
                </p>
            </div>
        </div>
        <hr>
        <div class="row d-flex align-items-center">
            <div class="col-md-7 col-lg-8">
                <p class="text-center text-md-left">
                    © 2021 Copyright:
                    <strong> Ali TÜRKER & Mehmet Eren BALLI</strong>
                </p>

            </div>
            <div class="col-md-5 col-lg-4 ml-lg-0">
                <div class="text-center text-md-right">
                    <ul class="list-unstyled list-inline">
                        <li class="list-inline-item">
                            <a class="btn-floating btn-sm rgba-white-slight mx-1">
                                <i class="fa fa-facebook-f"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="btn-floating btn-sm rgba-white-slight mx-1">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="btn-floating btn-sm rgba-white-slight mx-1">
                                <i class="fa fa-google-plus"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="btn-floating btn-sm rgba-white-slight mx-1">
                                <i class="fa fa-linkedin"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

Views/Shared/PartialViews/_Navbar.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<MyUser> SignInManager
@inject UserManager<MyUser> UserManager

<header>
    <nav class="navbar navbar-expand-lg smart-scroll navbar-light bg-light nav-pills fixed-top p-3" id="navbar">

        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <font class="text-info text-uppercase navbar-brand"><b>degistir.org</b></font>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse justify-content-end align-items-center" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item" id="index">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"
                       style="margin-right:20px;">Ana Sayfa <span class="sr-only">(current)</span></a>
                </li>


                @if (SignInManager.IsSignedIn(User))
                {
                    
                    <li class="nav-item">
                        <p class="nav-link">Merhaba, @UserManager.GetUserName(User)!</p>
                    </li>
                    <li class="nav-item">
                        <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button id="logout" type="submit" class="nav-link btn btn-link text-dark">Çıkış Yap</button>
                        </form>
                    </li>

                    MyUser user = await UserManager.GetUserAsync(User);
                    if (user != null && user.IsAdmin)
                    {
                        <li class="nav-item">
                            <a id="manage" class="nav-link" asp-area="" asp-controller="Announcements" asp-action="Index">Duyuruları Yönet</a>
                        </li>
                    }

                } 
                else
                {
                    <li class="nav-item">
                        <a class="nav-link" id="register" asp-area="Identity" asp-page="/Account/Register">Kayıt Ol</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="login" asp-area="Identity" asp-page="/Account/Login">Giriş Yap</a>
                    </li>
                }


            </ul>
            <form class="form-inline my-2 my-lg-0 px-90 nav-item" asp-controller="Titles" asp-action="Index" method="get">
                <input class="form-control mr-sm-2" placeholder="Ara" name="SearchString" />
                <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Ara" />
            </form>
        </div>

        <script>
            // add padding top to show content behind navbar
            $('body').css('padding-top', $('.navbar').outerHeight() + 'px');

            // detect scroll top or down
            let ss = $('.smart-scroll');

            if (ss.length > 0) { // check if element exists
                let last_scroll_top = 0;

                $(window).on('scroll', () => {
                    scroll_top = $(this).scrollTop();
                    //console.log(scroll_top);


                    if (scroll_top < last_scroll_top) {
                        ss.removeClass('scrolled-down').addClass('scrolled-up');
                    }
                    else if ($(window).scrollTop() > $('.navbar').outerHeight() * 0.75) {
                        ss.removeClass('scrolled-up').addClass('scrolled-down');
                    }
                    last_scroll_top = scroll_top;
                });
            }

        </script>

    </nav>
</header>